# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marvelous' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftGen', '~> 6.0'
  pod 'Alamofire', '~> 5.6.4'
  pod 'Swinject', '~> 2.8.3'
	pod 'SwinjectAutoregistration', '2.8.3'
	pod 'KeychainAccess', '~> 4.2.2'
	pod 'Kingfisher', '~> 7.0'
end
